### ISSUE TITLE
404 ?

### ISSUE THREAD

**Issue by NeeRaj-2401** [Bnyro/FindX#3]
![Screenshot_2023-02-13-01-00-56-41_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/88180887/218332914-e62cebbf-495f-4828-a0f8-a12a5b61797e.jpg)

**Comment by Bnyro** [comment]
Yeah, Piped is down :/

**Comment by Bnyro** [comment]
Seems to be up again :)
