### ISSUE TITLE
Freezes on phone 

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/FindX#5]
When I use this on my phone, it freezes sometimes, especially when surfing images, so site needs some optimization

**Comment by HotarunIchijou** [comment]
Also note, that it freezes only on chromium-based browsers

**Comment by Bnyro** [comment]
I'm using a Chromium based browser and can't reproduce any lags.
FindX doesn't use any JavaScript so that can't be an issue.
The only thing I can image is slow response times because it's running on a rather slow server, but that shouldn't cause any lags.

**Comment by HotarunIchijou** [comment]
But it does, while on firefox based it doesn't 

Chromium based
https://user-images.githubusercontent.com/113282550/229376063-77e8ed46-0ade-4026-8b02-c93fd58a271a.mp4

Firefox based
https://user-images.githubusercontent.com/113282550/229376071-33675c45-6bb3-40de-9839-50c56dabe3c1.mp4

**Comment by Bnyro** [comment]
Hmm, that's very weird. I'll try to reproduce it with Chromium/Bromite, but I'd suspect it to be a browser issue.

**Comment by HotarunIchijou** [comment]
Also I've reproduced this on Kiwi browser, which is also chromium based
